export enum SegmentAlertEnumCommands {
  INIT = 'SEGMENT_ALERT_INIT',
  ORIGIN = 'SEGMENT_ALERT_ORIGIN',
  DESTINATION = 'SEGMENT_ALERT_DESTINATION',
  LINE_AND_SENSE = 'SEGMENT_ALERT_LINE_AND_SENSE',
}
