export enum SeeTicketsEnumCommand {
  GET_USER_MOVIE_STATE = 'GET_USER_MOVIE_STATE',
  GET_USER_SHOWTIME_STATE = 'GET_USER_SHOWTIME_STATE',
  SEND_USER_SHOWTIMES_STATE = 'SEND_USER_SHOWTIMES_STATE',
  LAST_STEP = 'LAST_STEP',
}
