export enum SeeBusEnumCommands {
  SEE_BUS_INIT_STATE = 'SEE_BUS_INIT_STATE',
  SEE_BUS_ORIGIN_STATE = 'SEE_BUS_ORIGIN_STATE',
  SEE_BUS_DESTINATION_STATE = 'SEE_BUS_DESTINATION_STATE',
  SEE_BUS_MAP_STATE = 'SEE_BUS_MAP_STATE',
  LAST_STEP = 'LAST_STEP',
}
